<?php

namespace PN\SeoBundle\Repository;

/**
 * SeoSocialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeoSocialRepository extends \Doctrine\ORM\EntityRepository
{
}
